package:
  name: lua
  version: "5.1.4.8"

source:
  fn: lua-5.1.4.8.tar.gz
  url: http://downloads.sourceforge.net/project/lmod/lua-5.1.4.8.tar.gz

requirements:
  build:
    - gcc

  run:
    - libgcc
